#!/bin/sh
# This script was modified  from
# the 'magma' R package by Brian Smith which is licensed by
# under GNU GPL 3 or later.

# Cleans up after the auxiliary files that were created when installing
# the gmatrix package
#
echo "Cleaning up after installing the gmatrix package"

for f in config.log config.status config.cache ; do
  if test -w $f ; then
    rm -f $f
  fi
done

cd src
make clean
rm -f Makefile

